version: "2"

services:
 nginx:
  container_name: nginx
  build: ./requirements/nginx
  depends_on:
   - wordpress
  ports:
   - "443:443"
  volumes:
   - wordpress_data:/var/www/html
  networks:
   - inception
 mariadb:
  container_name: mariadb
  build: ./requirements/mariadb
  environment:
   - MARIADB_DB
   - MARIADB_ROOT_PW
   - MARIADB_ID
   - MARIADB_PW
  volumes:
   - mariadb_data:/var/lib/mysql
  expose:
   - "3306"
  networks:
   - inception
 wordpress:
  container_name: wordpress
  build: ./requirements/wordpress
  depends_on:
   - mariadb
  env_file:
   - .env
  expose:
   - "9000"
  volumes:
   - wordpress_data:/var/www/html
  networks:
   - inception

networks:
 inception:

volumes:
 mariadb_data:
  driver: local
  driver_opts:
   type: volume
   o: bind
   device: /Users/dahee/Desktop/dahpark/data/db
 wordpress_data:
  driver: local
  driver_opts:
   type: volume
   o: bind
   device: /Users/dahee/Desktop/dahpark/data/site
