# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dahpark <dahpark@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/04/23 13:58:58 by dahpark           #+#    #+#              #
#    Updated: 2022/04/23 14:27:37 by dahpark          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: "2"

services:
 nginx:
  container_name: nginx
  build: ./requirements/nginx
  depends_on:
   - wordpress
  restart: on-failure
  ports:
   - "443:443"
  volumes:
   - wordpress_data:/var/www/html
  networks:
   - inception
 mariadb:
  container_name: mariadb
  build: ./requirements/mariadb
  restart: on-failure
  environment:
   - MARIADB_DB
   - MARIADB_ROOT_PW
   - MARIADB_ID
   - MARIADB_PW
  volumes:
   - mariadb_data:/var/lib/mysql
  expose:
   - "3306"
  networks:
   - inception
 wordpress:
  container_name: wordpress
  build: ./requirements/wordpress
  depends_on:
   - mariadb
  restart: on-failure
  env_file:
   - .env
  expose:
   - "9000"
  volumes:
   - wordpress_data:/var/www/html
  networks:
   - inception

networks:
 inception:

volumes:
 mariadb_data:
  driver: local
  driver_opts:
   type: volume
   o: bind
   device: /home/dahpark/data/db
 wordpress_data:
  driver: local
  driver_opts:
   type: volume
   o: bind
   device: /home/dahpark/data/site
