version: "2"

services:
 nginx:
  container_name: nginx
  build: ./requirements/nginx
  ports:
   - "443:443"
 mariadb:
  container_name: mariadb
  build: ./requirements/mariadb
  environment:
   - MARIADB_DB
   - MARIADB_ROOT_PW
   - MARIADB_ID
   - MARIADB_PW
